[build-system]
requires = ["scikit-build-core>=0.3.3", "pybind11", "NumPy", "matplotlib"]
build-backend = "scikit_build_core.build"

[project]
name = "fdaPDE"
version = "1.0.0"
description="The python wrapper to the fdaPDE library for physics-informed spatial and functional data analysis."
readme = "README.md"
authors = [
  { name = "Alessandro Palummo", email = "alessandro.palummo@polimi.it" },
  { name = "Ilenia Di Battista" },
]
requires-python = ">=3.7"